spring:
  messages:
    basename: message
  h2:
    console: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: 'none'
    show-sql: true

# jwt secret key
app:
  jwt:
    secret-key: "4D635166546A576E5A7234753778214125442A472D4B614E645267556B587032"