server:
  port: 8082

logging:
  level:
    web: debug

spring:
  messages:
    basename: message
  datasource:
    url: "jdbc:mysql://replica-public-dev-db.cwfjsyuf7mwr.ap-northeast-2.rds.amazonaws.com:3306/fivekim"
    username: admin
    password: admin123
    jpa:
      hibernate:
        ddl-auto: 'none'
      show-sql: true
      properties:
        format_sql: true
        use_sql_comments: true
  jpa:
    hibernate:
      ddl-auto: 'none'
    show-sql: true

# jwt secret key
app:
  jwt:
    secret-key: "4D635166546A576E5A7234753778214125442A472D4B614E645267556B587032"

# 프론트 서버
front:
  url:
    http: "http://oh-kim.com"
    https: "https://oh-kim.com"